version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-taskmanager}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-taskmanager}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      JWT_SECRET: xXs52jwF9Uw4CPhzI1uPSbBxZvx0oyGhioe60LkCkuI=
    depends_on:
      - postgres
    develop:
      watch:
        - path: ./backend/src
          target: /app/src
          action: sync
        - path: ./backend/pom.xml
          target: /app/pom.xml
          action: sync

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - API_URL=${API_URL:-http://localhost:8080}
    depends_on:
      - backend
    develop:
      watch:
        - path: ./frontend/src
          target: /app/src
          action: sync
        - path: ./frontend/package.json
          target: /app/package.json
          action: sync

volumes:
  postgres_data:
