spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

jwt:
  # In production, set this environment variable with a secure random key
  # Example: export JWT_SECRET=$(openssl rand -base64 32)
  secret: ${JWT_SECRET:xXs52jwF9Uw4CPhzI1uPSbBxZvx0oyGhioe60LkCkuI=}
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

logging:
  level:
    root: INFO
    com.taskmanager: DEBUG
    org.springframework.security: DEBUG
